name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  kondo:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: DeLaGuardo/clojure-lint-action@master
      with:
        check-name: Run clj-kondo
        clj-kondo-args: >-
          --lint
          src
          test
        github_token: ${{ secrets.GITHUB_TOKEN }}

  tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Prepare JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@12.1
      with:
        cli: 1.11.1.1413
    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: v1-${{ hashFiles('./deps.edn') }}-tests
        restore-keys: |
          v1-${{ hashFiles('./deps.edn') }}-
          v1-
    - run: clojure -X:dev:test
      name: Run tests
      env:
        CI: TRUE

  whitespace-linter:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Prepare JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@12.1
      with:
        cli: 1.11.1.1413
    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: v1-${{ hashFiles('./deps.edn') }}-whitespace-linter
        restore-keys: |
          v1-${{ hashFiles('./deps.edn') }}-
          v1-
    - run: clojure -T:whitespace-linter
      name: Run whitespace linter

  check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Prepare JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@12.1
      with:
        cli: 1.11.1.1413
    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: v1-${{ hashFiles('./deps.edn') }}-check
        restore-keys: |
          v1-${{ hashFiles('./deps.edn') }}-
          v1-
    - run: clojure -M:check
      name: Check namespaces

  # codecov:
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v4.1.0
  #   - name: Prepare JDK 17
  #     uses: actions/setup-java@v3
  #     with:
  #       java-version: 17
  #       distribution: 'temurin'
  #   - name: Setup Clojure
  #     uses: DeLaGuardo/setup-clojure@12.1
  #     with:
  #       cli: 1.11.1.1413
  #   - name: Restore cache
  #     uses: actions/cache@v3
  #     with:
  #       path: |
  #         ~/.m2/repository
  #         ~/.gitlibs
  #         ~/.deps.clj
  #       key: v1-${{ hashFiles('./deps.edn') }}-codecov
  #       restore-keys: |
  #         v1-${{ hashFiles('./deps.edn') }}-
  #         v1-
  #   - run: clojure -X:dev:cloverage
  #     name: Run tests with Cloverage
  #   - name: Upload results to codecov.io
  #     uses: codecov/codecov-action@v3
  #     with:
  #       files: ./target/coverage/codecov.json

  codespell:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: codespell-project/actions-codespell@v2
        with:
          ignore_words_file: .codespellignore
